# Generated by Django 4.2.11 on 2024-03-13 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("common", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Data",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("blood_oxygen", models.CharField(max_length=5)),
                ("user_name", models.CharField(max_length=100)),
                ("terminal_id", models.CharField(max_length=100)),
                ("time_stamp", models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name="Terminal",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("terminal_id", models.CharField(max_length=100)),
                ("terminal_ip", models.CharField(max_length=15)),
            ],
        ),
    ]
