# Generated by Django 4.2.11 on 2024-03-14 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("common", "0003_user_password"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="address",
        ),
        migrations.RemoveField(
            model_name="user",
            name="phone_number",
        ),
        migrations.AddField(
            model_name="user",
            name="user_type",
            field=models.IntegerField(default=2),
        ),
    ]
