# Generated by Django 4.2.11 on 2024-03-14 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("common", "0004_remove_user_address_remove_user_phone_number_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="password",
            field=models.CharField(default="123456", max_length=100),
        ),
    ]
