# Generated by Django 4.2.11 on 2024-03-14 08:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("common", "0006_data_activaty"),
    ]

    operations = [
        migrations.RenameField(
            model_name="data",
            old_name="activaty",
            new_name="activity",
        ),
    ]
