# Generated by Django 4.2.11 on 2024-03-14 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("common", "0007_rename_activaty_data_activity"),
    ]

    operations = [
        migrations.AlterField(
            model_name="data",
            name="blood_oxygen",
            field=models.CharField(max_length=20),
        ),
    ]
